---
title: "Tidycensus Markdown"
author: "E Chin Li"
date: "09/06/2023"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: cerulean
---
# Lab example

The whole work of the lab example is hidden, including the results and plots.
```{r setup, include=FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(rmarkdown)
```

```{r setup_packages1, warning = FALSE, eval = FALSE}
install.packages('tidyverse')
install.packages('tidycensus')
install.packages('sf')
```

```{r setup_packages2, warning = FALSE, message = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
```

```{r setup_kableextra, warning = FALSE, message = FALSE, include = FALSE}
install.packages('kableExtra', repos='https://cran.ma.imperial.ac.uk/')
library(kableExtra)
```

```{r load_key, warning = FALSE, eval = FALSE}
census_api_key("ee5bb303d562a134a5fc2cdbc4ab53c8d0ca7629", overwrite = TRUE)
```

```{r load_variables, cache = TRUE}

acs_variable_list.2020 <- load_variables(2020, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)

acs_variable_list.2016 <- load_variables(2016, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)
```

```{r acs_vars}
acs_vars <- c("B01001_001E", # ACS total Pop estimate
              "B25002_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B02001_002E", # People describing themselves as "white alone"
              "B06009_006E") # Total graduate or professional degree
```

```{r get_acs_2020, cache = TRUE, message = FALSE, warning = FALSE}
acsTractsPHL.2020 <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = acs_vars, 
                             geometry = FALSE, 
                             state = "PA", 
                             county = "Philadelphia", 
                             output = "wide") 
```

```{r do_some_dplyr, cache = TRUE}
acsTractsPHL.2020 <- acsTractsPHL.2020 %>%
  dplyr::select (GEOID, NAME, all_of(acs_vars))

acsTractsPHL.2020 <- acsTractsPHL.2020 %>%
  rename (total_pop.2020 = B01001_001E,
          total_HU.2020 = B25002_001E,
          total_vacant.2020 = B25002_003E,
          med_HH_Income.2020 = B19013_001E,
          total_White.2020 = B02001_002E,
          total_GradDeg.2020 = B06009_006E)

acsTractsPHL.2020 <- acsTractsPHL.2020 %>%
  mutate(vacancyPct.2020 = total_vacant.2020/total_HU.2020,
         pctWhite.2020   = total_White.2020/total_pop.2020)
```

```{r get_acs_2016, cache = TRUE, message = FALSE}
acsTractsPHL.2016 <- get_acs(geography = "tract",
                             year = 2016, 
                             variables = acs_vars,
                             geometry = FALSE,
                             state = "PA", 
                             county = "Philadelphia",
                             output = "wide") %>%
  dplyr::select (GEOID, NAME, all_of(acs_vars)) %>% 
  rename (total_pop.2016 = B01001_001E,
          total_HU.2016 = B25002_001E,
          total_vacant.2016 = B25002_003E,
          med_HH_Income.2016 = B19013_001E,
          total_White.2016 = B02001_002E,
          total_GradDeg.2016 = B06009_006E) %>%
  mutate(vacancyPct.2016 = total_vacant.2016/total_HU.2016,
         pctWhite.2016 = total_White.2016/total_pop.2016)
```

```{r left_join_tracts, cache = TRUE}
allACS <- left_join(acsTractsPHL.2016, acsTractsPHL.2020,
                    by= c("GEOID"))
```

```{r do_mutates, cache = TRUE}
allACS <- allACS %>%
  mutate(change_med_HH_Income = med_HH_Income.2020 - (med_HH_Income.2016 * 1.08), 
         change_Grad_Degree_Pct = (total_GradDeg.2020/total_pop.2020)-(total_GradDeg.2016/total_pop.2016))

```

```{r base_r_summaries_NA_example, cache = TRUE, include = FALSE}
mean(allACS$change_med_HH_Income)
```

```{r base_r_summaries_NA_rm, cache = TRUE, include = FALSE}
mean(allACS$change_med_HH_Income, na.rm = TRUE)

median(allACS$change_med_HH_Income, na.rm = TRUE)
```

```{r basic_histogram, cache = TRUE, include = FALSE}
hist(allACS$change_med_HH_Income)
```

```{r ggplot_histogram_simple, warning = FALSE, cache = TRUE, message = FALSE, include = FALSE}
ggplot(allACS) +
  geom_histogram(aes(change_med_HH_Income))
  
```

```{r ggplot_histogram, warning = FALSE, cache = TRUE, include = FALSE}
ggplot(allACS)+
  geom_histogram(aes(change_med_HH_Income), binwidth = 5000)+
  labs(
    title = "Change in Philadelphia HH median income by tract, 2016-2020",
    caption = "Data: US Census Bureau, ACS 5-year estimates",
    x="Change in Med HH Income (2020 dollars)", 
       y="Number of tracts")
  
```

```{r summaryTable, cache = TRUE}
summaryTable <- allACS %>%
  summarize(mean_change_HH_Income = mean(change_med_HH_Income, na.rm = TRUE),
            med_change_HH_Income = median(change_med_HH_Income, na.rm = TRUE))
```

```{r myTracts, cache = TRUE}

myTracts <- c("42101023500", 
              "42101023600", 
              "42101023700", 
              "42101025300", 
              "42101025400",
              "42101025500", 
              "42101025600", 
              "42101038800")

allACS <- allACS %>%
  mutate(mtAiry = ifelse(GEOID %in% myTracts, "MT AIRY", "REST OF PHILADELPHIA"))
```

```{r summary_table_2, cache = TRUE, message = FALSE, warning = FALSE}
summaryTable2 <- allACS %>%
  group_by(mtAiry) %>%
  summarize(mean_change_HH_Income = mean(change_med_HH_Income, na.rm = TRUE),
            med_change_HH_Income = median(change_med_HH_Income, na.rm = TRUE))
```

```{r ggplot_histogram_2, warning = FALSE, cache = TRUE,include = FALSE}
ggplot(allACS)+
  geom_histogram(aes(change_med_HH_Income),
                 binwidth = 5000)+
  labs(
    title = "Change in Philadelphia HH median income by tract, 2016-2020",
    caption = "Data: US Census Bureau, ACS 5-year estimates",
    x="Change in Med HH Income (2020 dollars)", 
       y="Number of tracts")+
  facet_wrap(~mtAiry, scales = "free")
  
```

```{r ggplot_point1, warning = FALSE, cache = TRUE, include=FALSE}
ggplot(allACS)+
  geom_point(aes(x =med_HH_Income.2016 * 1.08, 
                 y = med_HH_Income.2020,
                 color = mtAiry))+
  geom_abline(intercept = 0, slope = 1)+
  labs(
    title = "2020 Median HH Income as a Function of 2016 Median HH Income",
    subtitle = "All figures in 2020 dollars",
    caption = "Data: US Census Bureau, ACS 5-year estimates",
    x="Med HH Income 2016 ($)", 
    y="Med HH Income 2020 ($)")
  
```

```{r ggplot_point2, warning = FALSE, cache = TRUE, message = FALSE,include = FALSE}
ggplot(allACS)+
  geom_point(aes(x = 100* pctWhite.2020, 
                 y = med_HH_Income.2020,
                 color = mtAiry))+
  geom_smooth(aes(x = 100* pctWhite.2020, 
                  y = med_HH_Income.2020), 
              method = "lm", se = FALSE)+
  labs(
    title = "2020 Median HH Income as a Function of Pct White",
    subtitle = "All figures in 2020 dollars",
    caption = "Data: US Census Bureau, ACS 5-year estimates",
    x="Pct. Residents Identifying as 'White Only'", 
    y="Med HH Income 2020 ($)")
  
```

```{r spatial_tidycensus, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
acsTractsPHL.2020.sf <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = acs_vars, 
                             geometry = TRUE, 
                             state = "PA", 
                             county = "Philadelphia", 
                             output = "wide") %>% 
  dplyr::select (GEOID, NAME, all_of(acs_vars)) %>%
  rename (total_pop.2020 = B01001_001E,
          total_HU.2020 = B25002_001E,
          total_vacant.2020 = B25002_003E,
          med_HH_Income.2020 = B19013_001E,
          total_White.2020 = B02001_002E,
          total_GradDeg.2020 = B06009_006E) %>%
  mutate(vacancyPct.2020 = total_vacant.2020/total_HU.2020,
         pctWhite.2020 = total_White.2020/total_pop.2020) %>%
  mutate(mtAiry = ifelse(GEOID %in% myTracts, "MT AIRY", "REST OF PHILADELPHIA")) %>%
  st_as_sf(crs = 4326) # Turn shp into sf object and project as WGS84
```

```{r ggplot_geom_sf, warning = FALSE, cache = TRUE,include = FALSE, result = 'HIDE'}
ggplot()+
  geom_sf(data = acsTractsPHL.2020.sf, aes(fill = pctWhite.2020),
          color = "transparent")+
  geom_sf(data = acsTractsPHL.2020.sf %>%
            filter(mtAiry == "MT AIRY") %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those identifying as 'white only' by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

```{r setup_packages3, warning = FALSE, message = FALSE}
library(plotly)
```
# Assignment

## (a)

```{r do_mutates2, cache=FALSE}
fig <- ggplot(allACS)+
  geom_point(aes(x = total_vacant.2016, 
                 y = total_vacant.2020,
                 color = mtAiry))+
  geom_abline(intercept = 0, slope = 1)+
  labs(
    title = "2020 Vacant Housing Units as a Function of 2016 Vacant Housing Units",
    caption = "Data: US Census Bureau, ACS 5-year estimates",
    x="Vacant Housing Units 2016", 
    y="Vacant Housing Units 2020")
ggplotly(fig)
```

## (b)

```{r spatial_tidycensus3, message=FALSE, warning=FALSE, cache=TRUE, include = FALSE}
acsTractsPHL.2016.sf <- get_acs(geography = "tract",
                             year = 2016, 
                             variables = acs_vars, 
                             geometry = TRUE, 
                             state = "PA", 
                             county = "Philadelphia", 
                             output = "wide") %>% 
  dplyr::select (GEOID, NAME, all_of(acs_vars)) %>%
  rename (total_pop.2016 = B01001_001E,
          total_HU.2016 = B25002_001E,
          total_vacant.2016 = B25002_003E,
          med_HH_Income.2016 = B19013_001E,
          total_White.2016 = B02001_002E,
          total_GradDeg.2016 = B06009_006E) %>%
  mutate(vacancyPct.2016 = total_vacant.2016/total_HU.2016) %>%
 mutate(mtAiry = ifelse(GEOID %in% myTracts, "MT AIRY", "REST OF PHILADELPHIA")) %>%
  st_as_sf(crs = 4326)
```
```{r ggplot_assign, message=FALSE, warning=FALSE, cache=TRUE}
fig <- ggplot()+
  geom_sf(data = acsTractsPHL.2016.sf, aes(fill = vacancyPct.2016),
          color = "transparent")+
  geom_sf(data = acsTractsPHL.2016.sf %>%
            filter(mtAiry == "MT AIRY") %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Vacancy Percentage of Total Housing Units by Tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
ggplotly(fig) 
```

## (c)

```{r group_summarise, warning = FALSE, message = FALSE}
allACS %>%                                    
  group_by(mtAiry) %>%                 
  summarise_at(vars(total_vacant.2020),    
               list(mean_number = mean),
               na.rm = TRUE) %>% 
  kbl(caption = "Mean Number of Vacant Housing Units(per tract)") %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "bordered", "condensed"))
```
